### PR TITLE
FEAT: Rhode Island

### PR DESCRIPTION
**Pull request by tlyon3**
FYI, the dates are all the exact same

### CODE REVIEW

**Comment by cc7768** [comment]
Hmm -- At the top of the page they have the following documentation:

> Service Description: THIS IS JUST A TEST> THIS IS FAKE DATA> THIS IS JUST A TEST

I suspect that this is not real data or that they've changed their mind about how to use this service -- Would be useful to know which.

**Comment by cc7768** [comment]
Additionally, it looks like there is a many to one mapping of RI towns to counties (see, http://www.dlt.ri.gov/lmi/maps/county.htm). If this is real data, it would be useful to convert things into county data.

**Comment by tlyon3** [comment]
The dashboard website is using the `COVID_Public_Map_TEST` service. That is why I used that. So either the description hasn't been updated, or the dashboard shouldn't be used.

**Comment by tlyon3** [comment]
It also looks like the only county level data is the number of confirmed cases. Every other column is a state wide total

**Comment by tlyon3** [comment]
ah. This is because it's not actually using the ArcGIS data. It's using Google Data Studio

**Comment by cc7768** [comment]
The tests for this PR are failing. Would you make sure that they're passing so that I can review this?

We definitely want to collect the testing data at the city/town level -- It's displayed on their dashboard page (https://ri-department-of-health-covid-19-data-rihealth.hub.arcgis.com/) but I don't know where it is coming from.

**Comment by tlyon3** [comment]
Got it. Should I group it by the counties like I did the case counts?

**Comment by cc7768** [comment]
Yep -- That would be great.

We may add support for non-state/non-county geographies in the future, but, for now, we only can handle county/state geos.

**Pull request merged**
