### PR TITLE
ENH: Add texas case, death, test data

### PR DESCRIPTION
**Pull request by cc7768**

### CODE REVIEW

**Comment by sglyon** [comment]
The total tests data seems to be off:

Screen Shot 2020-07-31 at 10 14 36 AM


Screen Shot 2020-07-31 at 10 14 53 AM


Are you getting the test data from the "test and hospital" dashbaord here: https://txdshs.maps.arcgis.com/apps/opsdashboard/index.html#/0d8bdf9be927459d9cb11b9eaef6101f

note I found a link to the test and hospital dashboard in the bottom right of the county cases dashboard

**Comment by sglyon** [comment]
That dashboard also has statewide hospital coverage

image

**Review by sglyon — CHANGES_REQUESTED** [review]
Let's look into the county total tests and see if we can get the state hospital data

**Comment by cc7768** [comment]
With respect to the testing data, I should have left a note on this discrepancy. The discrepancy between state and county data exists for two reasons:

1. The tests being reported on their dashboard page are a mixture of viral and antibody tests. The standard used in most states is to report only viral tests which is why we couldn't use the downloadable time series that they publish in the excel file.
2. If you switch tabs, you'll see that there are ~1 million tests that are pending county assignment. This means that they won't show up in any particular county's numbers but that they show up on the state numbers.

For the hospital data, I chose not to scrape the data because (1) Covid Tracking Project already has decent coverage on these variables for the state and (2) we'll have a chance to revisit this when we decide what to do about region level hospital reporting (which is what TX does).

Screenshot from 2020-07-31 13-30-33

**Pull request merged**
