### PR TITLE
Update api documentation

### PR DESCRIPTION
**Pull request by cc7768**
This updates the documentation for the views in the api schema

There are a couple that don't have the up-to-date schema definition. I think you already have them somewhere so I didn't update them -- Maybe this is a good chance to update these definitions.

### CODE REVIEW

**Comment by sglyon** [comment]
Thanks, I can add the other definitions.

Do you know which ones you didn't update, so I can make sure not to miss any

**Comment by cc7768** [comment]
Just noticed you responded -- I'm pretty sure that the following need to be updated:

* `api_covid`
* `api_demographics`
* `api_economics`

Also note that this PR created a `states` and `counties` view in the API -- Let me know whether you think other information belongs there.

**Comment by sglyon** [comment]
ok thanks. I'll take a look

**Comment by sglyon** [comment]
@cc7768 looks like the demographics view was removed and has not been regenerated.... What's the plan here?

**Comment by sglyon** [comment]
sorry -- I understand now. I'll see what those definitions are in the db and move them into these files

**Pull request merged**
