### PR TITLE
Missouri

### PR DESCRIPTION
**Pull request by tlyon3**

### CODE REVIEW

**Comment by tlyon3** [comment]
The testing data columns are daily totals, not cumulative. I'm not sure how you want to roll that up/aggegrate that, so I left the columns as `[n]_daily`

**Comment by cc7768** [comment]
The tests seem to be failing on this. Could you investigate what's going on?

In terms of the daily totals vs cumulatives, is it a time-series of tests or only one day of tests? If it is a time-series, you should be able to use `pd.DataFrame.cumsum` to get the cumulative sum (make sure to sort dates first).

**Comment by tlyon3** [comment]
The problem is the timestamps provided by the dashboard don't include timezones. How would you like me to handle this? Assign the local timezone for the state, then convert to UTC?

**Comment by cc7768** [comment]
Tests are still failing -- It looks like the insert is failing. It looks like maybe you have getters that have `county` data and getters that have `fips` information and it is failing to insert both types. It's easiest to separate these into different classes (or write your own insert query).

I'm going to hold off giving this another review until tests pass.

**Comment by sglyon** [comment]
@cc7768  and @tlyon3 tests are failing because of the `black` check..

I cannot replicate locally or get black to make any changes when I try running it off this branch.

Will you please try it out and let me know what you get back?

**Comment by tlyon3** [comment]
I tried running `black src` locally and nothing changed...

**Pull request merged**
